// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmxfscewppgfdjaploki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxteGZzY2V3cHBnZmRqYXBsb2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDM4NDYsImV4cCI6MjA1ODQ3OTg0Nn0.zkWMFEAdTKg_SAottI0d9U52eXATKt8URrAXpsAX3pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);